version: '3.8'
services:
  proxy-nginx:
    build:
      context: ./WEB
      dockerfile: Dockerfile
    container_name: proxy-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/
      - ./certbot/:/etc/nginx/ssl/
    depends_on:
      - nestjs
    networks:
      network:
        ipv4_address: 10.5.0.2
    restart: unless-stopped

  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 10.5.0.3

  nestjs:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: nestjs
    depends_on:
      - postgres-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      network:
        ipv4_address: 10.5.0.4

volumes:
  db:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
